# Docker-compose file used for reference to wrap the launch lauch of the deployment image
# ```
# docker-compose run stack-builder
# ```

version: '3.7'

services:
  stack-builder:
    build:
      context: .
      dockerfile: Dockerfile.deploy
    network_mode: "host"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: '/home/ubuntu/.kube/config'
        target: /root/.kube/config
      - type: bind
        source: '/home/ubuntu/firm/trace-grapher'
        target: '/home/ubuntu/firm/trace-grapher'
    working_dir: '/home/ubuntu/firm/trace-grapher'
    command: sh -c "cd deploy-trace-grapher && make prepare-trace-grapher-namespace && make install-components"
